### PR TITLE
Fix safari flex prefix

### PR DESCRIPTION
**Pull request by jamielikeschickens**
Content not showing in Safari, vendor prefixes added to flex properties.

### CODE REVIEW

**Comment by m10l** [comment]
@jamielikeschickens :+1: Looks good. Might be worth adding some kind of auto vendor-prefix task? I've never used Jekyll so don't know how easy it is to slot in, no worries if it's a massive faff.

**Comment by jamielikeschickens** [comment]
@m10l I've never really used it myself either, not entirely sure what you mean by an auto vendor-prefix task?

**Comment by nouveller** [comment]
There is https://github.com/octopress/autoprefixer, which allows you to write un-prefixed code and this post processes your CSS/SCSS when Jekyll builds your site, adding the prefixes for you.

But, I don't think Github Pages support the use of this plugin/gem. Considering we only have one instance we need the prefixes for, this may be overkill.

**Comment by jamielikeschickens** [comment]
Yeah https://help.github.com/articles/using-jekyll-plugins-with-github-pages/ is the list of all the gems they have installed on the gh-pages system. 

For now I'd say it's probably okay it's only being used in the viewport, if it becomes more of a problem later it can be revisited.

**Pull request closed without merging**
