### PR TITLE
Add information about the participant token

### LINKED ISSUE #11: Add help text for API parts
We need to be able to explain where to find keys such as X-Rusic-Participant-Token in the API explorer. I suggest that we allow help text to be written for each `api-part` directive.

cc/ @nouveller thoughts?

### PR DESCRIPTION
**Pull request by adambutler**
Added some documentation about the participant token.

Fixes #11

### CODE REVIEW

**Comment by adambutler** [comment]
@nicholedwight @nouveller :eyes:

**Comment by nicholedwight** [comment]
@adambutler Only thing was the token didn't come back under `rusic_participant_token`, it was actually just `token`

**Comment by nouveller** [comment]
:+1:

**Comment by adambutler** [comment]
@nicholedwight good spot... this will be changing to `rusic_participant_token` when https://github.com/rusic/rusic/pull/563 goes live so I will leave both in the docs for now.

**Comment by nicholedwight** [comment]
@adambutler amazeballs 🐙

**Pull request merged**
